export const tagTypes = {
  auth: "Auth",
  users: "Users",
  content: "Content",
  subscription: "Subscription",
  hrAdmin: "HrAdmin",
  earing: "Earning",
  stat: "Stat",
  earningHistory: "EarningHistory",
  profile: "Profile",
  guidanceHub: "GuidanceHub",
  workplaceTags: "WorkplaceTags",
  communication: "communication",
  jobSearchHelp: "JobSearchHelp",
  policyAndRight: "PolicyAndRight",
  manageContent: "ManageContent",
  issueCategory: "IssueCategory",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.users,
  tagTypes.content,
  tagTypes.subscription,
  tagTypes.hrAdmin,
  tagTypes.earing,
  tagTypes.stat,
  tagTypes.earningHistory,
  tagTypes.hrAdmin,
  tagTypes.profile,
  tagTypes.guidanceHub,
  tagTypes.workplaceTags,
  tagTypes.communication,
  tagTypes.jobSearchHelp,
  tagTypes.policyAndRight,
  tagTypes.manageContent,
  tagTypes.issueCategory,
];
